package com.zs.project.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zs.project.greendao.NewData;
import com.zs.project.greendao.MovieData;

import com.zs.project.greendao.NewDataDao;
import com.zs.project.greendao.MovieDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newDataDaoConfig;
    private final DaoConfig movieDataDaoConfig;

    private final NewDataDao newDataDao;
    private final MovieDataDao movieDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newDataDaoConfig = daoConfigMap.get(NewDataDao.class).clone();
        newDataDaoConfig.initIdentityScope(type);

        movieDataDaoConfig = daoConfigMap.get(MovieDataDao.class).clone();
        movieDataDaoConfig.initIdentityScope(type);

        newDataDao = new NewDataDao(newDataDaoConfig, this);
        movieDataDao = new MovieDataDao(movieDataDaoConfig, this);

        registerDao(NewData.class, newDataDao);
        registerDao(MovieData.class, movieDataDao);
    }
    
    public void clear() {
        newDataDaoConfig.clearIdentityScope();
        movieDataDaoConfig.clearIdentityScope();
    }

    public NewDataDao getNewDataDao() {
        return newDataDao;
    }

    public MovieDataDao getMovieDataDao() {
        return movieDataDao;
    }

}
