package com.zs.project.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zs.project.greendao.MovieData;
import com.zs.project.greendao.NewData;

import com.zs.project.greendao.MovieDataDao;
import com.zs.project.greendao.NewDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig movieDataDaoConfig;
    private final DaoConfig newDataDaoConfig;

    private final MovieDataDao movieDataDao;
    private final NewDataDao newDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        movieDataDaoConfig = daoConfigMap.get(MovieDataDao.class).clone();
        movieDataDaoConfig.initIdentityScope(type);

        newDataDaoConfig = daoConfigMap.get(NewDataDao.class).clone();
        newDataDaoConfig.initIdentityScope(type);

        movieDataDao = new MovieDataDao(movieDataDaoConfig, this);
        newDataDao = new NewDataDao(newDataDaoConfig, this);

        registerDao(MovieData.class, movieDataDao);
        registerDao(NewData.class, newDataDao);
    }
    
    public void clear() {
        movieDataDaoConfig.clearIdentityScope();
        newDataDaoConfig.clearIdentityScope();
    }

    public MovieDataDao getMovieDataDao() {
        return movieDataDao;
    }

    public NewDataDao getNewDataDao() {
        return newDataDao;
    }

}
