package com.zs.project.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zs.project.greendao.ArticleData;
import com.zs.project.greendao.MovieDetailData;

import com.zs.project.greendao.ArticleDataDao;
import com.zs.project.greendao.MovieDetailDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articleDataDaoConfig;
    private final DaoConfig movieDetailDataDaoConfig;

    private final ArticleDataDao articleDataDao;
    private final MovieDetailDataDao movieDetailDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articleDataDaoConfig = daoConfigMap.get(ArticleDataDao.class).clone();
        articleDataDaoConfig.initIdentityScope(type);

        movieDetailDataDaoConfig = daoConfigMap.get(MovieDetailDataDao.class).clone();
        movieDetailDataDaoConfig.initIdentityScope(type);

        articleDataDao = new ArticleDataDao(articleDataDaoConfig, this);
        movieDetailDataDao = new MovieDetailDataDao(movieDetailDataDaoConfig, this);

        registerDao(ArticleData.class, articleDataDao);
        registerDao(MovieDetailData.class, movieDetailDataDao);
    }
    
    public void clear() {
        articleDataDaoConfig.clearIdentityScope();
        movieDetailDataDaoConfig.clearIdentityScope();
    }

    public ArticleDataDao getArticleDataDao() {
        return articleDataDao;
    }

    public MovieDetailDataDao getMovieDetailDataDao() {
        return movieDetailDataDao;
    }

}
