package com.zs.project.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MOVIE_DATA".
*/
public class MovieDataDao extends AbstractDao<MovieData, Long> {

    public static final String TABLENAME = "MOVIE_DATA";

    /**
     * Properties of entity MovieData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ImageUrl = new Property(1, String.class, "imageUrl", false, "IMAGE_URL");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property Casts = new Property(3, String.class, "casts", false, "CASTS");
        public final static Property Genres = new Property(4, String.class, "genres", false, "GENRES");
        public final static Property Url = new Property(5, String.class, "url", false, "URL");
        public final static Property Average = new Property(6, float.class, "average", false, "AVERAGE");
    }


    public MovieDataDao(DaoConfig config) {
        super(config);
    }
    
    public MovieDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MOVIE_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"IMAGE_URL\" TEXT," + // 1: imageUrl
                "\"TITLE\" TEXT," + // 2: title
                "\"CASTS\" TEXT," + // 3: casts
                "\"GENRES\" TEXT," + // 4: genres
                "\"URL\" TEXT," + // 5: url
                "\"AVERAGE\" REAL NOT NULL );"); // 6: average
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MOVIE_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MovieData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(2, imageUrl);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String casts = entity.getCasts();
        if (casts != null) {
            stmt.bindString(4, casts);
        }
 
        String genres = entity.getGenres();
        if (genres != null) {
            stmt.bindString(5, genres);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(6, url);
        }
        stmt.bindDouble(7, entity.getAverage());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MovieData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(2, imageUrl);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String casts = entity.getCasts();
        if (casts != null) {
            stmt.bindString(4, casts);
        }
 
        String genres = entity.getGenres();
        if (genres != null) {
            stmt.bindString(5, genres);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(6, url);
        }
        stmt.bindDouble(7, entity.getAverage());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MovieData readEntity(Cursor cursor, int offset) {
        MovieData entity = new MovieData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // imageUrl
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // casts
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // genres
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // url
            cursor.getFloat(offset + 6) // average
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MovieData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setImageUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCasts(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setGenres(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUrl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setAverage(cursor.getFloat(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MovieData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MovieData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MovieData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
